### ISSUE TITLE
When this feature will be merged to webrpc core?

### ISSUE THREAD

**Issue by alinz** [golang-cz/webrpc-sse#1]
Hello @VojtechVitek,
I'm kind of curious to know when this experimental feature will be landed in webrpc core. Do you have templates available somewhere so I can play around with this SSE?

p.s. thanks for this :D

**Comment by VojtechVitek** [comment]
Hi @alinz, long time no see my friend!

We're heavily refactoring webrpc right now. Once we finish that work, we'll talk streaming .. and I'll try to submit templates for this project upstream ;)

**Comment by alinz** [comment]
closing this, and looking forward to have that feature in webrpc.
